name: Gradle Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: uname -a
        run: uname -a

      - name: java -version
        run: java -version

      - name: gradle --version
        run: ./gradlew --version

      - name: Build with Gradle
        run: ./gradlew build
